# Generated by Django 5.2 on 2025-08-11 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.TextField(null=True)),
                ('trabajo', models.CharField(blank=True, max_length=150, null=True)),
                ('rut', models.CharField(blank=True, max_length=150, null=True)),
                ('nombres', models.CharField(blank=True, max_length=250, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=150, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cms/images/profiles/fotos')),
                ('socialx', models.CharField(blank=True, max_length=200, null=True)),
                ('socialfb', models.CharField(blank=True, max_length=200, null=True)),
                ('socialig', models.CharField(blank=True, max_length=200, null=True)),
                ('socialyt', models.CharField(blank=True, max_length=200, null=True)),
                ('socialli', models.CharField(blank=True, max_length=200, null=True)),
                ('socialgit', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuna_profile', to='cms.comuna')),
                ('id_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_profile', to='cms.pais')),
                ('id_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_profile', to='cms.region')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'cms_profile',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='idx_profile_titulo')],
            },
        ),
    ]
