# Generated by Django 5.2 on 2025-05-05 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'cms_comunas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'cms_provincias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=150)),
                ('razonsocial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='cms/images/logos')),
                ('estado', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_empresa', to='cms.comuna')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'cms_empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('moneda', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'cms_pais',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='idx_pais_titulo')],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_comuna', to='cms.provincia'),
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_region', to='cms.pais')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'db_table': 'cms_regiones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_provincia', to='cms.region'),
        ),
        migrations.CreateModel(
            name='representante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('comunas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_representante', to='cms.comuna')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_representante', to='cms.empresa')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'cms_representante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='colegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_colegio', to='cms.comuna')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'cms_colegio',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='idx_colegio_titulo')],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['id'], name='idx_empresa_titulo'),
        ),
        migrations.AddIndex(
            model_name='comuna',
            index=models.Index(fields=['id'], name='idx_comuna_titulo'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['id'], name='idx_region_titulo'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['id'], name='idx_provincia_titulo'),
        ),
        migrations.AddIndex(
            model_name='representante',
            index=models.Index(fields=['id'], name='idx_representante_titulo'),
        ),
    ]
