# Generated by Django 5.2 on 2025-10-23 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'cms_comunas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'cms_departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('moneda', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'cms_pais',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_colegio', to='cms.comuna')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'cms_colegio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=150)),
                ('razonsocial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='cms/images/logos')),
                ('estado', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_empresa', to='cms.comuna')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'cms_empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_region', to='cms.pais')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'db_table': 'cms_regiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(null=True)),
                ('trabajo', models.CharField(blank=True, max_length=150, null=True)),
                ('rut', models.CharField(blank=True, max_length=150, null=True)),
                ('nombres', models.CharField(blank=True, max_length=250, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=150, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(upload_to='cms/images/profiles/fotos')),
                ('socialx', models.CharField(blank=True, max_length=200, null=True)),
                ('socialfb', models.CharField(blank=True, max_length=200, null=True)),
                ('socialig', models.CharField(blank=True, max_length=200, null=True)),
                ('socialyt', models.CharField(blank=True, max_length=200, null=True)),
                ('socialli', models.CharField(blank=True, max_length=200, null=True)),
                ('socialgit', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuna_profile', to='cms.comuna')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_profile', to='cms.pais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_profile', to='cms.region')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'cms_profile',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_comuna', to='cms.region'),
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('comunas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_representante', to='cms.comuna')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_representante', to='cms.empresa')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'cms_representante',
                'ordering': ['id'],
            },
        ),
    ]
