# Generated by Django 5.2 on 2025-05-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'cms_departamento',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='idx_departamento_titulo')],
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('trabajo', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='cms/images/profiles/fotos')),
                ('socialx', models.CharField(max_length=200)),
                ('socialfb', models.CharField(max_length=200)),
                ('socialig', models.CharField(max_length=200)),
                ('socialyt', models.CharField(max_length=200)),
                ('socialli', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_profile', to='cms.comuna')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_profile', to='cms.pais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'cms_profile',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='idx_profile_titulo')],
            },
        ),
    ]
