# Generated by Django 5.2 on 2025-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_profile_email_alter_profile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ap_paterno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombres',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
