# Generated by Django 5.2 on 2025-05-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_profile_ap_materno_profile_ap_paterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_profile', to='cms.region'),
        ),
    ]
