# Generated by Django 5.2 on 2025-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='socialgit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
