# Generated by Django 5.2.1 on 2025-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_profile_celular_profile_email_profile_socialgit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cms/images/profiles/fotos'),
        ),
    ]
