# Generated by Django 5.2.1 on 2025-05-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_profile_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='usuario',
        ),
    ]
