# Generated by Django 5.2 on 2025-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_rename_user_profile_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='codigo_telefono',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
