# Generated by Django 5.2 on 2025-05-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_pais_codigo_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='provincia',
        ),
        migrations.AddField(
            model_name='comuna',
            name='pais',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pais_comuna', to='cms.pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region_comuna', to='cms.region'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='provincia',
        ),
    ]
