# Generated by Django 5.2 on 2025-05-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_comuna_provincia_comuna_pais_comuna_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_comuna', to='cms.pais'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_comuna', to='cms.region'),
        ),
    ]
