# Generated by Django 5.2 on 2025-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='web/images/slides')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'db_table': 'slider',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['id'], name='idx_slider_titulo')],
            },
        ),
    ]
